language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t martin3421/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true martin3421/docker-react npm run test